insert into categories
  (id, name)
values
  ('auto', 'Auto'),
  ('beauty', 'Beauty'),
  ('books', 'Books'),
  ('business', 'Business'),
  ('comedy', 'Comedy'),
  ('education', 'Education'),
  ('entertainment', 'Entertainment'),
  ('family', 'Family'),
  ('fashion', 'Fashion'),
  ('food', 'Food'),
  ('games', 'Games'),
  ('health', 'Health'),
  ('hobbies', 'Hobbies'),
  ('lifestyle', 'Lifestyle'),
  ('music', 'Music'),
  ('news', 'News'),
  ('politics', 'Politics'),
  ('religion', 'Religion'),
  ('science', 'Science'),
  ('society', 'Society'),
  ('sports', 'Sports'),
  ('tech', 'Tech'),
  ('travel', 'Travel'),
  ('Canada', 'CA'),
  ('Mexico', 'MX');