name: EPG Grabber

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to grab (Glob Pattern: *, {sit1,site2} ...)'
        required: true
        default: '{beinsports.com,sat.tv,shahid.mbc.net,canalplus.com}'
      days:
        description: 'Number of days to grab'
        required: true
        default: '2'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '7'
      date:
        description: 'Start date (YYYY-MM-DD format, defaults to today)'
        required: false
        type: string
      maxConnections:
        required: true
        default: '5'
      delay:
        required: true
        default: '0'
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm install
          npm run postinstall
      
      - name: Get current date
        if: inputs.date == ''
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"
        
      - name: Run EPG grabber
        env:
          S3_ENDPOINT: https://oboyvbpfsemflqoiqpnr.supabase.co/storage/v1/s3
          S3_REGION: eu-west-3
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_ACCESS_SECRET: ${{ secrets.S3_ACCESS_SECRET }}
        run: |
          npm run grab -- \
            --site="${{ inputs.site }}" \
            --days=${{ inputs.days }} \
            --date=${{ inputs.date || steps.date.outputs.time }} \
            --output=s3://epg-data/site={site}/channel={channel}/year={year}/month={month}/day={day}/lang={lang}/guide.xml \
            --maxConnections=${{ inputs.maxConnections }} \
            --delay=${{ inputs.delay }}
